// Vercel serverless function: POST /api/checklist-lookup
// Body: { sport: string, year: number, manufacturer: string }
//
// Called automatically by Capture.tsx right before saving a newly scanned set. Resolves a
// real card_number -> player_name mapping for this set, checking three tiers in order:
//   1. The bundled, manually-sourced checklist library (api/_lib/checklists/) — fastest,
//      fully trusted (verified: true).
//   2. A previously auto-generated checklist cached in Supabase from an earlier save of
//      this exact sport/year/manufacturer (api/_lib/generatedChecklistStore.ts).
//   3. Never seen before: kick off a Claude generation call in the BACKGROUND
//      (api/_lib/checklistGenerate.ts) and respond immediately with found: false,
//      generating: true. Generating a full checklist can take well over a minute for
//      large vintage sets, which blew past Vercel's 60s function timeout when this used
//      to be awaited inline (confirmed via a 504 FUNCTION_INVOCATION_TIMEOUT in testing).
//      The save itself is never worth blocking on this — once generation finishes it's
//      cached, so the *next* save/view of this same set gets real names from tier 2.
// Tiers 2 and 3 are marked verified: false — Claude's knowledge of obscure
// inserts/variations can be wrong, so Capture.tsx surfaces a "please double-check" note
// for these instead of treating them as ground truth the way bundled files are.
import type { VercelRequest, VercelResponse } from '@vercel/node'
import { waitUntil } from '@vercel/functions'
import { lookupChecklist } from './_lib/checklistLookup.js'
import { getCachedGeneratedChecklist, saveGeneratedChecklist } from './_lib/generatedChecklistStore.js'
import { generateChecklist } from './_lib/checklistGenerate.js'

// Runs after the response has already been sent. waitUntil keeps the serverless function
// alive until this resolves instead of letting it freeze immediately post-response, which
// is what made the old fire-and-forget comment in this file (now removed) actually unsafe.
async function generateAndCacheInBackground(sport: string, year: number, manufacturer: string) {
  try {
    const generated = await generateChecklist({ sport, year, manufacturer })
    if (Object.keys(generated.names).length === 0) return
    await saveGeneratedChecklist(sport, year, manufacturer, generated)
  } catch {
    // Nothing to do — the next save of this set will simply retry generation from tier 3.
  }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' })
    return
  }

  const { sport, year, manufacturer } = req.body ?? {}
  if (!sport) {
    res.status(400).json({ error: 'sport is required' })
    return
  }

  // Tier 1: bundled checklist.
  const bundled = lookupChecklist({ sport, year: year ?? null, manufacturer: manufacturer ?? null })
  if (bundled.found && bundled.dataset) {
    res.status(200).json({
      found: true,
      verified: true,
      names: bundled.dataset.names,
      source: bundled.dataset.source,
      total_card_count: bundled.dataset.total_card_count,
    })
    return
  }

  // Generation needs a concrete year + manufacturer to key off of — without both, there's
  // nothing to look up or generate.
  if (!year || !manufacturer) {
    res.status(200).json({ found: false, names: {} })
    return
  }

  // Tier 2: previously generated + cached.
  try {
    const cached = await getCachedGeneratedChecklist(sport, year, manufacturer)
    if (cached) {
      res.status(200).json({
        found: true,
        verified: cached.verified,
        names: cached.names,
        source: 'Auto-generated by Claude from trained knowledge — not yet manually verified',
        total_card_count: cached.total_card_count,
      })
      return
    }
  } catch {
    // Cache read failing (e.g. Supabase env vars missing) shouldn't block falling through
    // to generation below — worst case this regenerates instead of reading a cache hit.
  }

  // Tier 3: never generated before. Kick off generation in the background (kept alive by
  // waitUntil past this response) and respond immediately — this set's first save proceeds
  // with no real names, but the cache will be warm for the next save/view of it.
  waitUntil(generateAndCacheInBackground(sport, year, manufacturer))
  res.status(200).json({ found: false, generating: true, names: {} })
}
